[build]
builder = "dockerfile"
dockerfilePath = "src/dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production.deploy]
numReplicas = 1
